# Generated by Django 5.2.3 on 2025-06-20 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Comedy", "Comedy"),
                            ("Drama", "Drama"),
                            ("Sci-Fi", "Sci-Fi"),
                            ("Horror", "Horror"),
                            ("Romance", "Romance"),
                            ("Thriller", "Thriller"),
                            ("Fantasy", "Fantasy"),
                            ("Animation", "Animation"),
                            ("Documentary", "Documentary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ]
                    ),
                ),
                ("poster_url", models.URLField()),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
