# Generated by Django 5.2.3 on 2025-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="created_at",),
        migrations.RemoveField(model_name="movie", name="slug",),
        migrations.RemoveField(model_name="movie", name="updated_at",),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie", name="genre", field=models.CharField(max_length=50),
        ),
    ]
