# Generated by Django 5.2.3 on 2025-06-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_remove_movie_created_at_remove_movie_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
